### PR TITLE
Support unittest2

### PR DESCRIPTION
**Pull request by jayvdb**
Also issue a warning for unittest2.TestCase subclasses

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
this code fails if unittest2 is not installed

**Comment by RonnyPfannschmidt** [comment]
instead try something like

```python
try:
  import unittest2
except ImportError:
  BASES = TestCase,
else:
  BASES = TestCase, unittest2.TestCase

...
isinstance(obj, BASES)
```

**Comment by tomviner** [comment]
Hi @jayvdb 
As far as I can see, we already support unittest2 because unittest2.TestCase is a subclass of unittest.TestCase. Your new test passes, even without a change to pytest_repeat.py

See the source here https://hg.python.org/unittest2/file/default/unittest2/case.py#l375

You can also see in pdb:
```python
(Pdb) inspect.getmro(request.cls)
(<class 'test_dummy.T'>, <class 'unittest2.case.TestCase'>, <class 'unittest.case.TestCase'>, <type 'object'>)
(Pdb) issubclass(request.cls, TestCase)
True
```

**Comment by tomviner** [comment]
You need to use `-s` to see the warning. (I tried `-rw` but that's just for internal pytest-warnings)

**Comment by jayvdb** [comment]
@tomviner hmm, that should be true. confusing :/
fwiw, we should make that a pytest warning, as mentioned at https://github.com/pytest-dev/pytest-repeat/issues/3#issuecomment-229937930 , but I couldnt see how to use the relevant warn methon from in `__pytest_repeat_step_number`

**Pull request closed without merging**
